version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mediscreennote:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb
